In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df = pd.read_csv('titanic_data.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,no,third,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,yes,first,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,yes,third,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,yes,first,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,no,third,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [9]:
df.drop(['PassengerId', 'Name', 'Ticket'], axis=1, inplace=True)

In [10]:
df.head()

  Survived Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0       no  third    male  22.0      1      0   7.2500   NaN        S
1      yes  first  female  38.0      1      0  71.2833   C85        C
2      yes  third  female  26.0      0      0   7.9250   NaN        S
3      yes  first  female  35.0      1      0  53.1000  C123        S
4       no  third    male  35.0      0      0   8.0500   NaN        S

In [11]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [12]:
df.drop('Cabin', axis=1, inplace=True) 
df.head()

  Survived Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       no  third    male  22.0      1      0   7.2500        S
1      yes  first  female  38.0      1      0  71.2833        C
2      yes  third  female  26.0      0      0   7.9250        S
3      yes  first  female  35.0      1      0  53.1000        S
4       no  third    male  35.0      0      0   8.0500        S

In [13]:
df.drop('Survived', axis=1, inplace=True)
df.head()

  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0  third    male  22.0      1      0   7.2500        S
1  first  female  38.0      1      0  71.2833        C
2  third  female  26.0      0      0   7.9250        S
3  first  female  35.0      1      0  53.1000        S
4  third    male  35.0      0      0   8.0500        S