### Filtering Based on String

In [245]:
import pandas as pd

data ={
    "Name": ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan', 'Judy',],
    "city": ['New York', 'Los Angeles', 'New Delhi', 'Houston', 'Newark', 'New Orleans', 'San Antonio', 'San Diego', 'Dallas', 'H Los Angeles'],
    "Department": ['HR', 'Finance', 'IT', 'Marketing', 'Sales', 'HR', 'Finance', 'IT', 'Marketing', 'Sales'],
    "Salary": [70000, 80000, 90000, 75000, 85000, 72000, 82000, 92000, 77000, 87000]
}

df = pd.DataFrame(data)
print(df)

      Name           city Department  Salary
0    Alice       New York         HR   70000
1      Bob    Los Angeles    Finance   80000
2  Charlie      New Delhi         IT   90000
3    David        Houston  Marketing   75000
4      Eve         Newark      Sales   85000
5    Frank    New Orleans         HR   72000
6    Grace    San Antonio    Finance   82000
7    Heidi      San Diego         IT   92000
8     Ivan         Dallas  Marketing   77000
9     Judy  H Los Angeles      Sales   87000

In [246]:
df.loc[df['city'].str.contains("New")]

      Name         city Department  Salary
0    Alice     New York         HR   70000
2  Charlie    New Delhi         IT   90000
4      Eve       Newark      Sales   85000
5    Frank  New Orleans         HR   72000

In [247]:
df.loc[df['city'].str.contains("new", case=False)] # case=False means it will ignore the case sensitivity. So it will match "New", "new", "NEW", etc.

      Name         city Department  Salary
0    Alice     New York         HR   70000
2  Charlie    New Delhi         IT   90000
4      Eve       Newark      Sales   85000
5    Frank  New Orleans         HR   72000

In [248]:
#start with "Los"
df.loc[df['city'].str.contains(r"^Los")] # ^ means starts with

  Name         city Department  Salary
1  Bob  Los Angeles    Finance   80000

In [249]:
#end with rk
df.loc[df['city'].str.contains(r"rk$")] # $ means ends with

    Name      city Department  Salary
0  Alice  New York         HR   70000
4    Eve    Newark      Sales   85000

In [250]:
#name start with vowel
df.loc[df['Name'].str.contains(r"^[AEIOUaeiou]")] # ^ means starts with and [AEIOUaeiou] means any of the characters in the brackets

    Name      city Department  Salary
0  Alice  New York         HR   70000
4    Eve    Newark      Sales   85000
8   Ivan    Dallas  Marketing   77000

In [251]:
#start with New or los
df.loc[df['city'].str.contains(r"(^New|Los)")] # ^ means starts with and (New|Los) means either New or Los

/var/folders/gg/nmkjyktn2ks12wkqpnyjr7mc0000gn/T/ipykernel_39647/3937092426.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df.loc[df['city'].str.contains(r"(^New|Los)")] # ^ means starts with and (New|Los) means either New or Los

      Name           city Department  Salary
0    Alice       New York         HR   70000
1      Bob    Los Angeles    Finance   80000
2  Charlie      New Delhi         IT   90000
4      Eve         Newark      Sales   85000
5    Frank    New Orleans         HR   72000
9     Judy  H Los Angeles      Sales   87000

 #### 12.2 Adding new Column and Saving the File

In [252]:
import pandas as pd
df = pd.read_csv('student_completed_data.csv')

In [253]:
#adding a new columnn with constant value
df['Country'] = 'Bangladesh'
df.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Country
0,PH0001,Alif Rahman,85.5,88.0,88.0,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,Bangladesh
1,PH0002,Fatima Akhter,66.5,NaN,NaN,In Progress,2024-08-11,2024-11-07,Mr. Karim,Dhaka,Bangladesh
2,PH0003,Imran Hossain,78.0,78.0,76.0,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,Bangladesh
3,PH0004,Jannatul Ferdous,79.0,44.0,44.0,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,Bangladesh
4,PH0005,Kamal Uddin,65.0,98.0,98.0,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,Bangladesh

In [254]:
#total marks
df['Total Marks'] = df['Data Structure Marks'] + df['Algorithm Marks'] + df['Python Marks']

In [255]:
df.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Country,Total Marks
0,PH0001,Alif Rahman,85.5,88.0,88.0,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,Bangladesh,261.5
1,PH0002,Fatima Akhter,66.5,NaN,NaN,In Progress,2024-08-11,2024-11-07,Mr. Karim,Dhaka,Bangladesh,NaN
2,PH0003,Imran Hossain,78.0,78.0,76.0,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,Bangladesh,232.0
3,PH0004,Jannatul Ferdous,79.0,44.0,44.0,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,Bangladesh,167.0
4,PH0005,Kamal Uddin,65.0,98.0,98.0,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,Bangladesh,261.0

In [256]:
import numpy as np
#A+ in Data Structure if marks >= 80
df['Data Structure Grade'] = np.where(df['Data Structure Marks'] >= 80, 'A+', np.where(df['Data Structure Marks'] >= 70, 'A', np.where(df['Data Structure Marks'] >= 60, 'B', np.where(df['Data Structure Marks'] >= 50, 'C', np.where(df['Data Structure Marks'] >= 40, 'D', 'F')))))
df.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Country,Total Marks,Data Structure Grade
0,PH0001,Alif Rahman,85.5,88.0,88.0,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,Bangladesh,261.5,A+
1,PH0002,Fatima Akhter,66.5,NaN,NaN,In Progress,2024-08-11,2024-11-07,Mr. Karim,Dhaka,Bangladesh,NaN,B
2,PH0003,Imran Hossain,78.0,78.0,76.0,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,Bangladesh,232.0,A
3,PH0004,Jannatul Ferdous,79.0,44.0,44.0,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,Bangladesh,167.0,A
4,PH0005,Kamal Uddin,65.0,98.0,98.0,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,Bangladesh,261.0,B

In [257]:
#first Name
df['First Name'] = df['FullName'].str.split().str[0]
df.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Country,Total Marks,Data Structure Grade,First Name
0,PH0001,Alif Rahman,85.5,88.0,88.0,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,Bangladesh,261.5,A+,Alif
1,PH0002,Fatima Akhter,66.5,NaN,NaN,In Progress,2024-08-11,2024-11-07,Mr. Karim,Dhaka,Bangladesh,NaN,B,Fatima
2,PH0003,Imran Hossain,78.0,78.0,76.0,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,Bangladesh,232.0,A,Imran
3,PH0004,Jannatul Ferdous,79.0,44.0,44.0,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,Bangladesh,167.0,A,Jannatul
4,PH0005,Kamal Uddin,65.0,98.0,98.0,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,Bangladesh,261.0,B,Kamal

In [258]:
df.to_csv('new_data.csv')

### 12.3 Checking Duplicates and Null Values in DF

In [259]:
import pandas as pd
data = {
    "Name": ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Bob', 'Grace', 'Heidi', 'David', 'Judy',],
    "city": ['New York', 'Los Angeles', 'New Delhi', 'Houston', 'Newark', 'New Orleans', 'San Antonio', 'San Diego', 'Dallas', 'H Los Angeles'],
    "score": [85, 90, 78, 92, 88, 95, 80, 91, 89, 94]
}

df = pd.DataFrame(data)
print(df)

      Name           city  score
0    Alice       New York     85
1      Bob    Los Angeles     90
2  Charlie      New Delhi     78
3    David        Houston     92
4      Eve         Newark     88
5      Bob    New Orleans     95
6    Grace    San Antonio     80
7    Heidi      San Diego     91
8    David         Dallas     89
9     Judy  H Los Angeles     94

In [260]:
#Unique and nunique
df['Name'].unique() # unique values in the Name column
len(df['Name'].unique()) # number of unique values in the Name column

8

In [261]:
df1 = pd.read_csv('new_data.csv')
print(df1.head())

   Unnamed: 0 StudentID          FullName  Data Structure Marks  \
0           0    PH0001       Alif Rahman                  85.5
1           1    PH0002     Fatima Akhter                  66.5
2           2    PH0003     Imran Hossain                  78.0
3           3    PH0004  Jannatul Ferdous                  79.0
4           4    PH0005       Kamal Uddin                  65.0

   Algorithm Marks  Python Marks CompletionStatus EnrollmentDate FinishedDate  \
0             88.0          88.0        Completed     2024-09-01   2024-12-23
1              NaN           NaN      In Progress     2024-08-11   2024-11-07
2             78.0          76.0        Completed     2024-05-08   2024-08-08
3             44.0          44.0        Completed     2024-07-05   2024-09-23
4             98.0          98.0        Completed     2024-02-01   2024-04-17

  Instructor Location     Country  Total Marks Data Structure Grade First Name
0  Ms. Salma   Khulna  Bangladesh        261.5                   A+       Alif
1  Mr. Karim    Dhaka  Bangladesh          NaN                    B     Fatima
2  Ms. Salma    Dhaka  Bangladesh        232.0                    A      Imran
3  Mr. Karim   Khulna  Bangladesh        167.0                    A   Jannatul
4  Mr. David   Sylhet  Bangladesh        261.0                    B      Kamal

In [262]:
print(len(df1['Data Structure Marks'].unique())) # number of unique values in the Data Structure Marks column

print(df1['Data Structure Marks'].nunique()) # number of unique values in the Data Structure Marks column

16
15

### check null

In [263]:
df1[df1['Data Structure Marks'].isnull()]

,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Country,Total Marks,Data Structure Grade,First Name
7,7,PH0008,Nadia Islam,NaN,NaN,98.0,In Progress,2024-03-22,2024-05-01,Ms. Salma,Khulna,Bangladesh,NaN,F,Nadia
17,17,PH0018,Babul Ahmed,NaN,78.0,78.0,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,Bangladesh,NaN,F,Babul
20,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangladesh,NaN,F,NaN

In [264]:
df1['Data Structure Marks'].isnull()# check if there are any missing values in the DataFrame

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17     True
18    False
19    False
20     True
Name: Data Structure Marks, dtype: bool

### 12.4 Handling Duplicates Values

In [265]:
import pandas as pd
data = {
    "Name": ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Bob', 'Alice', 'Heidi', 'David', 'Judy',],
    "city": ['New York', 'Los Angeles', 'New Delhi', 'Houston', 'Newark', 'Los Angeles', 'San Antonio', 'San Diego', 'Dallas', 'New York'],
    "score": [85, 90, 78, 92, 85, 90, 80, 91, 89, 94]
}
df = pd.DataFrame(data)
print(df)

      Name         city  score
0    Alice     New York     85
1      Bob  Los Angeles     90
2  Charlie    New Delhi     78
3    David      Houston     92
4      Eve       Newark     85
5      Bob  Los Angeles     90
6    Alice  San Antonio     80
7    Heidi    San Diego     91
8    David       Dallas     89
9     Judy     New York     94

In [266]:
df.duplicated().sum() # number of duplicate rows in the DataFrame

np.int64(1)

In [267]:
# delete duplicate rows
df.drop_duplicates()

      Name         city  score
0    Alice     New York     85
1      Bob  Los Angeles     90
2  Charlie    New Delhi     78
3    David      Houston     92
4      Eve       Newark     85
6    Alice  San Antonio     80
7    Heidi    San Diego     91
8    David       Dallas     89
9     Judy     New York     94

In [268]:
# premanently delete duplicate rows
df.drop_duplicates(inplace=True)
df

      Name         city  score
0    Alice     New York     85
1      Bob  Los Angeles     90
2  Charlie    New Delhi     78
3    David      Houston     92
4      Eve       Newark     85
6    Alice  San Antonio     80
7    Heidi    San Diego     91
8    David       Dallas     89
9     Judy     New York     94

In [269]:
df

      Name         city  score
0    Alice     New York     85
1      Bob  Los Angeles     90
2  Charlie    New Delhi     78
3    David      Houston     92
4      Eve       Newark     85
6    Alice  San Antonio     80
7    Heidi    San Diego     91
8    David       Dallas     89
9     Judy     New York     94

In [270]:
# name er basis a delete duplicate rows
df.drop_duplicates(subset=['Name'],keep='last')

      Name         city  score
1      Bob  Los Angeles     90
2  Charlie    New Delhi     78
4      Eve       Newark     85
6    Alice  San Antonio     80
7    Heidi    San Diego     91
8    David       Dallas     89
9     Judy     New York     94

In [271]:
df.drop_duplicates(subset=['city'],keep='last')

      Name         city  score
1      Bob  Los Angeles     90
2  Charlie    New Delhi     78
3    David      Houston     92
4      Eve       Newark     85
6    Alice  San Antonio     80
7    Heidi    San Diego     91
8    David       Dallas     89
9     Judy     New York     94

### 12.5 Handling Null Values

In [272]:
import pandas as pd

df = pd.read_csv('student_completed_data.csv')
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location
0,PH0001,Alif Rahman,85.5,88.0,88.0,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna
1,PH0002,Fatima Akhter,66.5,NaN,NaN,In Progress,2024-08-11,2024-11-07,Mr. Karim,Dhaka
2,PH0003,Imran Hossain,78.0,78.0,76.0,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka
3,PH0004,Jannatul Ferdous,79.0,44.0,44.0,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna
4,PH0005,Kamal Uddin,65.0,98.0,98.0,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet
5,PH0006,Laila Begum,90.0,13.0,13.0,In Progress,2024-09-07,2024-12-31,Mr. David,Khulna
6,PH0007,Mahmudul Hasan,85.0,98.0,33.0,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram
7,PH0008,Nadia Islam,NaN,NaN,98.0,In Progress,2024-03-22,2024-05-01,Ms. Salma,Khulna
8,PH0009,Omar Faruq,98.0,33.0,33.0,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka
9,PH0010,Priya Sharma,99.0,8.0,8.0,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka
10,PH0011,Rahim Sheikh,66.0,76.0,NaN,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet
11,PH0012,Sadia Chowdhury,78.0,57.0,57.0,In Progress,2024-08-04,2024-10-25,Mr. Karim,Sylhet
12,PH0013,Tanvir Ahmed,75.0,NaN,NaN,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka
13,PH0014,Urmi Akter,98.0,78.0,88.0,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet
14,PH0015,Wahiduzzaman,37.0,67.0,67.0,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi
15,PH0016,Ziaur Rahman,34.0,88.0,91.0,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi
16,PH0017,Afsana Mimi,27.0,NaN,NaN,Completed,2024-01-18,2024-03-16,Mr. David,Khulna
17,PH0018,Babul Ahmed,NaN,78.0,78.0,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka
18,PH0019,Faria Rahman,55.0,77.0,77.0,In Progress,2024-04-19,2024-08-17,Mr. Karim,Sylhet
19,PH0020,Tariq Hasan,65.0,87.0,87.0,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [206]:
df.dropna(how='all',inplace=True) #all values are NaN then drop that row anyway it will not drop any row because there is no row where all values are NaN

In [273]:
df.dropna(subset=['Python Marks','Algorithm Marks']) # drop rows where Python and Algorithm Marks are NaN

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location
0,PH0001,Alif Rahman,85.5,88.0,88.0,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna
2,PH0003,Imran Hossain,78.0,78.0,76.0,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka
3,PH0004,Jannatul Ferdous,79.0,44.0,44.0,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna
4,PH0005,Kamal Uddin,65.0,98.0,98.0,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet
5,PH0006,Laila Begum,90.0,13.0,13.0,In Progress,2024-09-07,2024-12-31,Mr. David,Khulna
6,PH0007,Mahmudul Hasan,85.0,98.0,33.0,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram
8,PH0009,Omar Faruq,98.0,33.0,33.0,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka
9,PH0010,Priya Sharma,99.0,8.0,8.0,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka
11,PH0012,Sadia Chowdhury,78.0,57.0,57.0,In Progress,2024-08-04,2024-10-25,Mr. Karim,Sylhet
13,PH0014,Urmi Akter,98.0,78.0,88.0,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet
14,PH0015,Wahiduzzaman,37.0,67.0,67.0,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi
15,PH0016,Ziaur Rahman,34.0,88.0,91.0,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi
17,PH0018,Babul Ahmed,NaN,78.0,78.0,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka
18,PH0019,Faria Rahman,55.0,77.0,77.0,In Progress,2024-04-19,2024-08-17,Mr. Karim,Sylhet
19,PH0020,Tariq Hasan,65.0,87.0,87.0,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna

In [274]:
df = pd.read_csv('student_completed_data.csv') # load your data into a DataFrame
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location
0,PH0001,Alif Rahman,85.5,88.0,88.0,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna
1,PH0002,Fatima Akhter,66.5,NaN,NaN,In Progress,2024-08-11,2024-11-07,Mr. Karim,Dhaka
2,PH0003,Imran Hossain,78.0,78.0,76.0,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka
3,PH0004,Jannatul Ferdous,79.0,44.0,44.0,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna
4,PH0005,Kamal Uddin,65.0,98.0,98.0,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet
5,PH0006,Laila Begum,90.0,13.0,13.0,In Progress,2024-09-07,2024-12-31,Mr. David,Khulna
6,PH0007,Mahmudul Hasan,85.0,98.0,33.0,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram
7,PH0008,Nadia Islam,NaN,NaN,98.0,In Progress,2024-03-22,2024-05-01,Ms. Salma,Khulna
8,PH0009,Omar Faruq,98.0,33.0,33.0,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka
9,PH0010,Priya Sharma,99.0,8.0,8.0,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka
10,PH0011,Rahim Sheikh,66.0,76.0,NaN,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet
11,PH0012,Sadia Chowdhury,78.0,57.0,57.0,In Progress,2024-08-04,2024-10-25,Mr. Karim,Sylhet
12,PH0013,Tanvir Ahmed,75.0,NaN,NaN,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka
13,PH0014,Urmi Akter,98.0,78.0,88.0,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet
14,PH0015,Wahiduzzaman,37.0,67.0,67.0,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi
15,PH0016,Ziaur Rahman,34.0,88.0,91.0,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi
16,PH0017,Afsana Mimi,27.0,NaN,NaN,Completed,2024-01-18,2024-03-16,Mr. David,Khulna
17,PH0018,Babul Ahmed,NaN,78.0,78.0,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka
18,PH0019,Faria Rahman,55.0,77.0,77.0,In Progress,2024-04-19,2024-08-17,Mr. Karim,Sylhet
19,PH0020,Tariq Hasan,65.0,87.0,87.0,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [275]:
df.fillna(0)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location
0,PH0001,Alif Rahman,85.5,88.0,88.0,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna
1,PH0002,Fatima Akhter,66.5,0.0,0.0,In Progress,2024-08-11,2024-11-07,Mr. Karim,Dhaka
2,PH0003,Imran Hossain,78.0,78.0,76.0,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka
3,PH0004,Jannatul Ferdous,79.0,44.0,44.0,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna
4,PH0005,Kamal Uddin,65.0,98.0,98.0,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet
5,PH0006,Laila Begum,90.0,13.0,13.0,In Progress,2024-09-07,2024-12-31,Mr. David,Khulna
6,PH0007,Mahmudul Hasan,85.0,98.0,33.0,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram
7,PH0008,Nadia Islam,0.0,0.0,98.0,In Progress,2024-03-22,2024-05-01,Ms. Salma,Khulna
8,PH0009,Omar Faruq,98.0,33.0,33.0,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka
9,PH0010,Priya Sharma,99.0,8.0,8.0,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka
10,PH0011,Rahim Sheikh,66.0,76.0,0.0,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet
11,PH0012,Sadia Chowdhury,78.0,57.0,57.0,In Progress,2024-08-04,2024-10-25,Mr. Karim,Sylhet
12,PH0013,Tanvir Ahmed,75.0,0.0,0.0,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka
13,PH0014,Urmi Akter,98.0,78.0,88.0,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet
14,PH0015,Wahiduzzaman,37.0,67.0,67.0,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi
15,PH0016,Ziaur Rahman,34.0,88.0,91.0,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi
16,PH0017,Afsana Mimi,27.0,0.0,0.0,Completed,2024-01-18,2024-03-16,Mr. David,Khulna
17,PH0018,Babul Ahmed,0.0,78.0,78.0,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka
18,PH0019,Faria Rahman,55.0,77.0,77.0,In Progress,2024-04-19,2024-08-17,Mr. Karim,Sylhet
19,PH0020,Tariq Hasan,65.0,87.0,87.0,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna
20,0,0,0.0,0.0,0.0,0,0,0,0,0

In [276]:
df.fillna({'FullName': 'Unknown'}, inplace=True)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location
0,PH0001,Alif Rahman,85.5,88.0,88.0,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna
1,PH0002,Fatima Akhter,66.5,NaN,NaN,In Progress,2024-08-11,2024-11-07,Mr. Karim,Dhaka
2,PH0003,Imran Hossain,78.0,78.0,76.0,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka
3,PH0004,Jannatul Ferdous,79.0,44.0,44.0,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna
4,PH0005,Kamal Uddin,65.0,98.0,98.0,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet
5,PH0006,Laila Begum,90.0,13.0,13.0,In Progress,2024-09-07,2024-12-31,Mr. David,Khulna
6,PH0007,Mahmudul Hasan,85.0,98.0,33.0,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram
7,PH0008,Nadia Islam,NaN,NaN,98.0,In Progress,2024-03-22,2024-05-01,Ms. Salma,Khulna
8,PH0009,Omar Faruq,98.0,33.0,33.0,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka
9,PH0010,Priya Sharma,99.0,8.0,8.0,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka
10,PH0011,Rahim Sheikh,66.0,76.0,NaN,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet
11,PH0012,Sadia Chowdhury,78.0,57.0,57.0,In Progress,2024-08-04,2024-10-25,Mr. Karim,Sylhet
12,PH0013,Tanvir Ahmed,75.0,NaN,NaN,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka
13,PH0014,Urmi Akter,98.0,78.0,88.0,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet
14,PH0015,Wahiduzzaman,37.0,67.0,67.0,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi
15,PH0016,Ziaur Rahman,34.0,88.0,91.0,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi
16,PH0017,Afsana Mimi,27.0,NaN,NaN,Completed,2024-01-18,2024-03-16,Mr. David,Khulna
17,PH0018,Babul Ahmed,NaN,78.0,78.0,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka
18,PH0019,Faria Rahman,55.0,77.0,77.0,In Progress,2024-04-19,2024-08-17,Mr. Karim,Sylhet
19,PH0020,Tariq Hasan,65.0,87.0,87.0,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna
20,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [277]:
df.fillna({'Python Marks': df['Python Marks'].mean(), 'Algorithm Marks': df['Algorithm Marks'].mean(), 'Data Structure Marks': df['Data Structure Marks'].mean()}, inplace=True)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location
0,PH0001,Alif Rahman,85.500000,88.00,88.00,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna
1,PH0002,Fatima Akhter,66.500000,66.75,64.75,In Progress,2024-08-11,2024-11-07,Mr. Karim,Dhaka
2,PH0003,Imran Hossain,78.000000,78.00,76.00,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka
3,PH0004,Jannatul Ferdous,79.000000,44.00,44.00,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna
4,PH0005,Kamal Uddin,65.000000,98.00,98.00,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet
5,PH0006,Laila Begum,90.000000,13.00,13.00,In Progress,2024-09-07,2024-12-31,Mr. David,Khulna
6,PH0007,Mahmudul Hasan,85.000000,98.00,33.00,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram
7,PH0008,Nadia Islam,71.166667,66.75,98.00,In Progress,2024-03-22,2024-05-01,Ms. Salma,Khulna
8,PH0009,Omar Faruq,98.000000,33.00,33.00,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka
9,PH0010,Priya Sharma,99.000000,8.00,8.00,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka
10,PH0011,Rahim Sheikh,66.000000,76.00,64.75,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet
11,PH0012,Sadia Chowdhury,78.000000,57.00,57.00,In Progress,2024-08-04,2024-10-25,Mr. Karim,Sylhet
12,PH0013,Tanvir Ahmed,75.000000,66.75,64.75,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka
13,PH0014,Urmi Akter,98.000000,78.00,88.00,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet
14,PH0015,Wahiduzzaman,37.000000,67.00,67.00,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi
15,PH0016,Ziaur Rahman,34.000000,88.00,91.00,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi
16,PH0017,Afsana Mimi,27.000000,66.75,64.75,Completed,2024-01-18,2024-03-16,Mr. David,Khulna
17,PH0018,Babul Ahmed,71.166667,78.00,78.00,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka
18,PH0019,Faria Rahman,55.000000,77.00,77.00,In Progress,2024-04-19,2024-08-17,Mr. Karim,Sylhet
19,PH0020,Tariq Hasan,65.000000,87.00,87.00,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna
20,NaN,Unknown,71.166667,66.75,64.75,NaN,NaN,NaN,NaN,NaN

In [278]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location
0,PH0001,Alif Rahman,85.500000,88.00,88.00,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna
1,PH0002,Fatima Akhter,66.500000,66.75,64.75,In Progress,2024-08-11,2024-11-07,Mr. Karim,Dhaka
2,PH0003,Imran Hossain,78.000000,78.00,76.00,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka
3,PH0004,Jannatul Ferdous,79.000000,44.00,44.00,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna
4,PH0005,Kamal Uddin,65.000000,98.00,98.00,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet
5,PH0006,Laila Begum,90.000000,13.00,13.00,In Progress,2024-09-07,2024-12-31,Mr. David,Khulna
6,PH0007,Mahmudul Hasan,85.000000,98.00,33.00,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram
7,PH0008,Nadia Islam,71.166667,66.75,98.00,In Progress,2024-03-22,2024-05-01,Ms. Salma,Khulna
8,PH0009,Omar Faruq,98.000000,33.00,33.00,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka
9,PH0010,Priya Sharma,99.000000,8.00,8.00,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka
10,PH0011,Rahim Sheikh,66.000000,76.00,64.75,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet
11,PH0012,Sadia Chowdhury,78.000000,57.00,57.00,In Progress,2024-08-04,2024-10-25,Mr. Karim,Sylhet
12,PH0013,Tanvir Ahmed,75.000000,66.75,64.75,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka
13,PH0014,Urmi Akter,98.000000,78.00,88.00,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet
14,PH0015,Wahiduzzaman,37.000000,67.00,67.00,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi
15,PH0016,Ziaur Rahman,34.000000,88.00,91.00,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi
16,PH0017,Afsana Mimi,27.000000,66.75,64.75,Completed,2024-01-18,2024-03-16,Mr. David,Khulna
17,PH0018,Babul Ahmed,71.166667,78.00,78.00,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka
18,PH0019,Faria Rahman,55.000000,77.00,77.00,In Progress,2024-04-19,2024-08-17,Mr. Karim,Sylhet
19,PH0020,Tariq Hasan,65.000000,87.00,87.00,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna
20,NaN,Unknown,71.166667,66.75,64.75,NaN,NaN,NaN,NaN,NaN

### 12.6 Statistical Functions in Pandas

In [279]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location
0,PH0001,Alif Rahman,85.500000,88.00,88.00,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna
1,PH0002,Fatima Akhter,66.500000,66.75,64.75,In Progress,2024-08-11,2024-11-07,Mr. Karim,Dhaka
2,PH0003,Imran Hossain,78.000000,78.00,76.00,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka
3,PH0004,Jannatul Ferdous,79.000000,44.00,44.00,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna
4,PH0005,Kamal Uddin,65.000000,98.00,98.00,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet
5,PH0006,Laila Begum,90.000000,13.00,13.00,In Progress,2024-09-07,2024-12-31,Mr. David,Khulna
6,PH0007,Mahmudul Hasan,85.000000,98.00,33.00,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram
7,PH0008,Nadia Islam,71.166667,66.75,98.00,In Progress,2024-03-22,2024-05-01,Ms. Salma,Khulna
8,PH0009,Omar Faruq,98.000000,33.00,33.00,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka
9,PH0010,Priya Sharma,99.000000,8.00,8.00,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka
10,PH0011,Rahim Sheikh,66.000000,76.00,64.75,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet
11,PH0012,Sadia Chowdhury,78.000000,57.00,57.00,In Progress,2024-08-04,2024-10-25,Mr. Karim,Sylhet
12,PH0013,Tanvir Ahmed,75.000000,66.75,64.75,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka
13,PH0014,Urmi Akter,98.000000,78.00,88.00,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet
14,PH0015,Wahiduzzaman,37.000000,67.00,67.00,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi
15,PH0016,Ziaur Rahman,34.000000,88.00,91.00,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi
16,PH0017,Afsana Mimi,27.000000,66.75,64.75,Completed,2024-01-18,2024-03-16,Mr. David,Khulna
17,PH0018,Babul Ahmed,71.166667,78.00,78.00,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka
18,PH0019,Faria Rahman,55.000000,77.00,77.00,In Progress,2024-04-19,2024-08-17,Mr. Karim,Sylhet
19,PH0020,Tariq Hasan,65.000000,87.00,87.00,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna
20,NaN,Unknown,71.166667,66.75,64.75,NaN,NaN,NaN,NaN,NaN

In [280]:
df.dropna() # drop rows where any value is NaN

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location
0,PH0001,Alif Rahman,85.500000,88.00,88.00,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna
1,PH0002,Fatima Akhter,66.500000,66.75,64.75,In Progress,2024-08-11,2024-11-07,Mr. Karim,Dhaka
2,PH0003,Imran Hossain,78.000000,78.00,76.00,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka
3,PH0004,Jannatul Ferdous,79.000000,44.00,44.00,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna
4,PH0005,Kamal Uddin,65.000000,98.00,98.00,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet
5,PH0006,Laila Begum,90.000000,13.00,13.00,In Progress,2024-09-07,2024-12-31,Mr. David,Khulna
6,PH0007,Mahmudul Hasan,85.000000,98.00,33.00,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram
7,PH0008,Nadia Islam,71.166667,66.75,98.00,In Progress,2024-03-22,2024-05-01,Ms. Salma,Khulna
8,PH0009,Omar Faruq,98.000000,33.00,33.00,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka
9,PH0010,Priya Sharma,99.000000,8.00,8.00,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka
10,PH0011,Rahim Sheikh,66.000000,76.00,64.75,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet
11,PH0012,Sadia Chowdhury,78.000000,57.00,57.00,In Progress,2024-08-04,2024-10-25,Mr. Karim,Sylhet
12,PH0013,Tanvir Ahmed,75.000000,66.75,64.75,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka
13,PH0014,Urmi Akter,98.000000,78.00,88.00,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet
14,PH0015,Wahiduzzaman,37.000000,67.00,67.00,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi
15,PH0016,Ziaur Rahman,34.000000,88.00,91.00,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi
16,PH0017,Afsana Mimi,27.000000,66.75,64.75,Completed,2024-01-18,2024-03-16,Mr. David,Khulna
17,PH0018,Babul Ahmed,71.166667,78.00,78.00,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka
18,PH0019,Faria Rahman,55.000000,77.00,77.00,In Progress,2024-04-19,2024-08-17,Mr. Karim,Sylhet
19,PH0020,Tariq Hasan,65.000000,87.00,87.00,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna

In [281]:
print('Total Marks',df['Data Structure Marks'].sum()) # sum of the Data Structure Marks column
print('Average Marks',df['Data Structure Marks'].mean()) # mean of the Data Structure Marks column
print('Maximum Marks',df['Data Structure Marks'].max()) # max of the Data Structure Marks column
print('Minimum Marks',df['Data Structure Marks'].min()) # min of the Data Structure Marks column

Total Marks 1494.5000000000002
Average Marks 71.16666666666667
Maximum Marks 99.0
Minimum Marks 27.0

In [216]:
# mode > highest frequency value
print('Mode Marks',df['Data Structure Marks'].mode()) # mode of the Data Structure Marks column

Mode Marks 0    71.166667
Name: Data Structure Marks, dtype: float64

In [282]:
#standard deviation
print('Standard Deviation Marks',df['Data Structure Marks'].std()) # standard deviation of

Standard Deviation Marks 20.026232796010337

In [283]:
# corelation matrix
print('Correlation Matrix')
df[['Python Marks', 'Algorithm Marks']].corr()

Correlation Matrix

                 Python Marks  Algorithm Marks
Python Marks         1.000000         0.788583
Algorithm Marks      0.788583         1.000000

In [284]:
#sum in diffrent column 
df[['Data Structure Marks', 'Algorithm Marks']].sum()

Data Structure Marks    1494.50
Algorithm Marks         1401.75
dtype: float64

In [285]:
#sum in diffrent row
df[['Data Structure Marks', 'Algorithm Marks']].sum(axis=1)

0     173.500000
1     133.250000
2     156.000000
3     123.000000
4     163.000000
5     103.000000
6     183.000000
7     137.916667
8     131.000000
9     107.000000
10    142.000000
11    135.000000
12    141.750000
13    176.000000
14    104.000000
15    122.000000
16     93.750000
17    149.166667
18    132.000000
19    152.000000
20    137.916667
dtype: float64

In [286]:
df['Total Marks'] = df.iloc[::,2:5].sum(axis=1)
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Alif Rahman,85.500000,88.00,88.00,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,261.500000
1,PH0002,Fatima Akhter,66.500000,66.75,64.75,In Progress,2024-08-11,2024-11-07,Mr. Karim,Dhaka,198.000000
2,PH0003,Imran Hossain,78.000000,78.00,76.00,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,232.000000
3,PH0004,Jannatul Ferdous,79.000000,44.00,44.00,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,167.000000
4,PH0005,Kamal Uddin,65.000000,98.00,98.00,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,261.000000
5,PH0006,Laila Begum,90.000000,13.00,13.00,In Progress,2024-09-07,2024-12-31,Mr. David,Khulna,116.000000
6,PH0007,Mahmudul Hasan,85.000000,98.00,33.00,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,216.000000
7,PH0008,Nadia Islam,71.166667,66.75,98.00,In Progress,2024-03-22,2024-05-01,Ms. Salma,Khulna,235.916667
8,PH0009,Omar Faruq,98.000000,33.00,33.00,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,164.000000
9,PH0010,Priya Sharma,99.000000,8.00,8.00,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,115.000000
10,PH0011,Rahim Sheikh,66.000000,76.00,64.75,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,206.750000
11,PH0012,Sadia Chowdhury,78.000000,57.00,57.00,In Progress,2024-08-04,2024-10-25,Mr. Karim,Sylhet,192.000000
12,PH0013,Tanvir Ahmed,75.000000,66.75,64.75,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,206.500000
13,PH0014,Urmi Akter,98.000000,78.00,88.00,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,264.000000
14,PH0015,Wahiduzzaman,37.000000,67.00,67.00,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,171.000000
15,PH0016,Ziaur Rahman,34.000000,88.00,91.00,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,213.000000
16,PH0017,Afsana Mimi,27.000000,66.75,64.75,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,158.500000
17,PH0018,Babul Ahmed,71.166667,78.00,78.00,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,227.166667
18,PH0019,Faria Rahman,55.000000,77.00,77.00,In Progress,2024-04-19,2024-08-17,Mr. Karim,Sylhet,209.000000
19,PH0020,Tariq Hasan,65.000000,87.00,87.00,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,239.000000
20,NaN,Unknown,71.166667,66.75,64.75,NaN,NaN,NaN,NaN,NaN,202.666667

In [287]:
df.describe()

       Data Structure Marks  Algorithm Marks  Python Marks  Total Marks
count             21.000000        21.000000     21.000000    21.000000
mean              71.166667        66.750000     64.750000   202.666667
std               20.026233        24.422326     25.825375    42.379904
min               27.000000         8.000000      8.000000   115.000000
25%               65.000000        66.750000     57.000000   171.000000
50%               71.166667        67.000000     64.750000   206.750000
75%               85.000000        78.000000     87.000000   232.000000
max               99.000000        98.000000     98.000000   264.000000

### 12.7 Apply Function in DF

In [288]:
# min max scaling

mn = df['Total Marks'].min()
mx = df['Total Marks'].max()

df['Scaled Marks'] = df['Total Marks'].apply(lambda x: (x - mn) / (mx - mn))

In [224]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Scaled Marks
0,PH0001,Alif Rahman,85.500000,88.00,88.00,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,261.500000,0.983221
1,PH0002,Fatima Akhter,66.500000,66.75,64.75,In Progress,2024-08-11,2024-11-07,Mr. Karim,Dhaka,198.000000,0.557047
2,PH0003,Imran Hossain,78.000000,78.00,76.00,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,232.000000,0.785235
3,PH0004,Jannatul Ferdous,79.000000,44.00,44.00,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,167.000000,0.348993
4,PH0005,Kamal Uddin,65.000000,98.00,98.00,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,261.000000,0.979866
5,PH0006,Laila Begum,90.000000,13.00,13.00,In Progress,2024-09-07,2024-12-31,Mr. David,Khulna,116.000000,0.006711
6,PH0007,Mahmudul Hasan,85.000000,98.00,33.00,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,216.000000,0.677852
7,PH0008,Nadia Islam,71.166667,66.75,98.00,In Progress,2024-03-22,2024-05-01,Ms. Salma,Khulna,235.916667,0.811521
8,PH0009,Omar Faruq,98.000000,33.00,33.00,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,164.000000,0.328859
9,PH0010,Priya Sharma,99.000000,8.00,8.00,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,115.000000,0.000000
10,PH0011,Rahim Sheikh,66.000000,76.00,64.75,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,206.750000,0.615772
11,PH0012,Sadia Chowdhury,78.000000,57.00,57.00,In Progress,2024-08-04,2024-10-25,Mr. Karim,Sylhet,192.000000,0.516779
12,PH0013,Tanvir Ahmed,75.000000,66.75,64.75,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,206.500000,0.614094
13,PH0014,Urmi Akter,98.000000,78.00,88.00,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,264.000000,1.000000
14,PH0015,Wahiduzzaman,37.000000,67.00,67.00,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,171.000000,0.375839
15,PH0016,Ziaur Rahman,34.000000,88.00,91.00,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,213.000000,0.657718
16,PH0017,Afsana Mimi,27.000000,66.75,64.75,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,158.500000,0.291946
17,PH0018,Babul Ahmed,71.166667,78.00,78.00,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,227.166667,0.752796
18,PH0019,Faria Rahman,55.000000,77.00,77.00,In Progress,2024-04-19,2024-08-17,Mr. Karim,Sylhet,209.000000,0.630872
19,PH0020,Tariq Hasan,65.000000,87.00,87.00,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,239.000000,0.832215
20,NaN,Unknown,71.166667,66.75,64.75,NaN,NaN,NaN,NaN,NaN,202.666667,0.588367

In [289]:
#custom buid function

def greading_system(marks):
    if marks >= 260:
        return 'A+'
    elif marks >= 250:
        return 'A'
    elif marks >= 240:
        return 'A-'
    else:
        return 'F'
    
df['Grade'] = df['Total Marks'].apply(greading_system)

In [290]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Scaled Marks,Grade
0,PH0001,Alif Rahman,85.500000,88.00,88.00,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,261.500000,0.983221,A+
1,PH0002,Fatima Akhter,66.500000,66.75,64.75,In Progress,2024-08-11,2024-11-07,Mr. Karim,Dhaka,198.000000,0.557047,F
2,PH0003,Imran Hossain,78.000000,78.00,76.00,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,232.000000,0.785235,F
3,PH0004,Jannatul Ferdous,79.000000,44.00,44.00,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,167.000000,0.348993,F
4,PH0005,Kamal Uddin,65.000000,98.00,98.00,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,261.000000,0.979866,A+
5,PH0006,Laila Begum,90.000000,13.00,13.00,In Progress,2024-09-07,2024-12-31,Mr. David,Khulna,116.000000,0.006711,F
6,PH0007,Mahmudul Hasan,85.000000,98.00,33.00,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,216.000000,0.677852,F
7,PH0008,Nadia Islam,71.166667,66.75,98.00,In Progress,2024-03-22,2024-05-01,Ms. Salma,Khulna,235.916667,0.811521,F
8,PH0009,Omar Faruq,98.000000,33.00,33.00,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,164.000000,0.328859,F
9,PH0010,Priya Sharma,99.000000,8.00,8.00,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,115.000000,0.000000,F
10,PH0011,Rahim Sheikh,66.000000,76.00,64.75,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,206.750000,0.615772,F
11,PH0012,Sadia Chowdhury,78.000000,57.00,57.00,In Progress,2024-08-04,2024-10-25,Mr. Karim,Sylhet,192.000000,0.516779,F
12,PH0013,Tanvir Ahmed,75.000000,66.75,64.75,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,206.500000,0.614094,F
13,PH0014,Urmi Akter,98.000000,78.00,88.00,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,264.000000,1.000000,A+
14,PH0015,Wahiduzzaman,37.000000,67.00,67.00,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,171.000000,0.375839,F
15,PH0016,Ziaur Rahman,34.000000,88.00,91.00,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,213.000000,0.657718,F
16,PH0017,Afsana Mimi,27.000000,66.75,64.75,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,158.500000,0.291946,F
17,PH0018,Babul Ahmed,71.166667,78.00,78.00,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,227.166667,0.752796,F
18,PH0019,Faria Rahman,55.000000,77.00,77.00,In Progress,2024-04-19,2024-08-17,Mr. Karim,Sylhet,209.000000,0.630872,F
19,PH0020,Tariq Hasan,65.000000,87.00,87.00,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,239.000000,0.832215,F
20,NaN,Unknown,71.166667,66.75,64.75,NaN,NaN,NaN,NaN,NaN,202.666667,0.588367,F

In [291]:
def marking_system(df):
    a = df['Data Structure Marks']*2
    b = df['Python Marks']*3
    c = df['Algorithm Marks']*4
    
    return a + b + c

df['Exceptional Marks'] = df.apply(marking_system, axis=1)

In [243]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,Instructor,Location,Total Marks,Scaled Marks,Grade,Exceptional Marks,Enrolment Year,Enrolment Month,Enrolment Day,Total time taken to complete
0,PH0001,Alif Rahman,85.500000,88.00,88.00,Completed,Ms. Salma,Khulna,261.500000,0.983221,A+,787.000000,2024.0,9.0,1.0,113.0
1,PH0002,Fatima Akhter,66.500000,66.75,64.75,In Progress,Mr. Karim,Dhaka,198.000000,0.557047,F,594.250000,2024.0,8.0,11.0,88.0
2,PH0003,Imran Hossain,78.000000,78.00,76.00,Completed,Ms. Salma,Dhaka,232.000000,0.785235,F,696.000000,2024.0,5.0,8.0,92.0
3,PH0004,Jannatul Ferdous,79.000000,44.00,44.00,Completed,Mr. Karim,Khulna,167.000000,0.348993,F,466.000000,2024.0,7.0,5.0,80.0
4,PH0005,Kamal Uddin,65.000000,98.00,98.00,Completed,Mr. David,Sylhet,261.000000,0.979866,A+,816.000000,2024.0,2.0,1.0,76.0
5,PH0006,Laila Begum,90.000000,13.00,13.00,In Progress,Mr. David,Khulna,116.000000,0.006711,F,271.000000,2024.0,9.0,7.0,115.0
6,PH0007,Mahmudul Hasan,85.000000,98.00,33.00,Completed,Mr. David,Chattogram,216.000000,0.677852,F,661.000000,2024.0,6.0,7.0,43.0
7,PH0008,Nadia Islam,71.166667,66.75,98.00,In Progress,Ms. Salma,Khulna,235.916667,0.811521,F,703.333333,2024.0,3.0,22.0,40.0
8,PH0009,Omar Faruq,98.000000,33.00,33.00,Completed,Mr. Karim,Dhaka,164.000000,0.328859,F,427.000000,2024.0,2.0,12.0,117.0
9,PH0010,Priya Sharma,99.000000,8.00,8.00,Completed,Mr. David,Dhaka,115.000000,0.000000,F,254.000000,2024.0,6.0,19.0,61.0
10,PH0011,Rahim Sheikh,66.000000,76.00,64.75,Completed,Mr. Karim,Sylhet,206.750000,0.615772,F,630.250000,2024.0,3.0,14.0,89.0
11,PH0012,Sadia Chowdhury,78.000000,57.00,57.00,In Progress,Mr. Karim,Sylhet,192.000000,0.516779,F,555.000000,2024.0,8.0,4.0,82.0
12,PH0013,Tanvir Ahmed,75.000000,66.75,64.75,Completed,Mr. David,Dhaka,206.500000,0.614094,F,611.250000,2024.0,6.0,7.0,57.0
13,PH0014,Urmi Akter,98.000000,78.00,88.00,Completed,Mr. David,Sylhet,264.000000,1.000000,A+,772.000000,2024.0,1.0,4.0,79.0
14,PH0015,Wahiduzzaman,37.000000,67.00,67.00,Completed,Mr. David,Rajshahi,171.000000,0.375839,F,543.000000,2024.0,2.0,22.0,84.0
15,PH0016,Ziaur Rahman,34.000000,88.00,91.00,Completed,Ms. Salma,Rajshahi,213.000000,0.657718,F,693.000000,2024.0,3.0,23.0,90.0
16,PH0017,Afsana Mimi,27.000000,66.75,64.75,Completed,Mr. David,Khulna,158.500000,0.291946,F,515.250000,2024.0,1.0,18.0,58.0
17,PH0018,Babul Ahmed,71.166667,78.00,78.00,Completed,Mr. David,Dhaka,227.166667,0.752796,F,688.333333,2024.0,6.0,23.0,89.0
18,PH0019,Faria Rahman,55.000000,77.00,77.00,In Progress,Mr. Karim,Sylhet,209.000000,0.630872,F,649.000000,2024.0,4.0,19.0,120.0
19,PH0020,Tariq Hasan,65.000000,87.00,87.00,Completed,Mr. Karim,Khulna,239.000000,0.832215,F,739.000000,2024.0,7.0,21.0,82.0
20,NaN,Unknown,71.166667,66.75,64.75,NaN,NaN,NaN,202.666667,0.588367,F,603.583333,NaN,NaN,NaN,NaN

### 12.8 DateTime and Timedelta

In [292]:
df['EnrollmentDate'] = pd.to_datetime(df['EnrollmentDate'])
df['EnrollmentDate']

0    2024-09-01
1    2024-08-11
2    2024-05-08
3    2024-07-05
4    2024-02-01
5    2024-09-07
6    2024-06-07
7    2024-03-22
8    2024-02-12
9    2024-06-19
10   2024-03-14
11   2024-08-04
12   2024-06-07
13   2024-01-04
14   2024-02-22
15   2024-03-23
16   2024-01-18
17   2024-06-23
18   2024-04-19
19   2024-07-21
20          NaT
Name: EnrollmentDate, dtype: datetime64[us]

In [293]:
df['Enrolment Year'] = df['EnrollmentDate'].dt.year
df['Enrolment Month'] = df['EnrollmentDate'].dt.month
df['Enrolment Day'] = df['EnrollmentDate'].dt.day

In [240]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,Instructor,Location,Total Marks,Scaled Marks,Grade,Exceptional Marks,Enrolment Year,Enrolment Month,Enrolment Day,Total time taken to complete
0,PH0001,Alif Rahman,85.500000,88.00,88.00,Completed,Ms. Salma,Khulna,261.500000,0.983221,A+,787.000000,2024.0,9.0,1.0,113.0
1,PH0002,Fatima Akhter,66.500000,66.75,64.75,In Progress,Mr. Karim,Dhaka,198.000000,0.557047,F,594.250000,2024.0,8.0,11.0,88.0
2,PH0003,Imran Hossain,78.000000,78.00,76.00,Completed,Ms. Salma,Dhaka,232.000000,0.785235,F,696.000000,2024.0,5.0,8.0,92.0
3,PH0004,Jannatul Ferdous,79.000000,44.00,44.00,Completed,Mr. Karim,Khulna,167.000000,0.348993,F,466.000000,2024.0,7.0,5.0,80.0
4,PH0005,Kamal Uddin,65.000000,98.00,98.00,Completed,Mr. David,Sylhet,261.000000,0.979866,A+,816.000000,2024.0,2.0,1.0,76.0
5,PH0006,Laila Begum,90.000000,13.00,13.00,In Progress,Mr. David,Khulna,116.000000,0.006711,F,271.000000,2024.0,9.0,7.0,115.0
6,PH0007,Mahmudul Hasan,85.000000,98.00,33.00,Completed,Mr. David,Chattogram,216.000000,0.677852,F,661.000000,2024.0,6.0,7.0,43.0
7,PH0008,Nadia Islam,71.166667,66.75,98.00,In Progress,Ms. Salma,Khulna,235.916667,0.811521,F,703.333333,2024.0,3.0,22.0,40.0
8,PH0009,Omar Faruq,98.000000,33.00,33.00,Completed,Mr. Karim,Dhaka,164.000000,0.328859,F,427.000000,2024.0,2.0,12.0,117.0
9,PH0010,Priya Sharma,99.000000,8.00,8.00,Completed,Mr. David,Dhaka,115.000000,0.000000,F,254.000000,2024.0,6.0,19.0,61.0
10,PH0011,Rahim Sheikh,66.000000,76.00,64.75,Completed,Mr. Karim,Sylhet,206.750000,0.615772,F,630.250000,2024.0,3.0,14.0,89.0
11,PH0012,Sadia Chowdhury,78.000000,57.00,57.00,In Progress,Mr. Karim,Sylhet,192.000000,0.516779,F,555.000000,2024.0,8.0,4.0,82.0
12,PH0013,Tanvir Ahmed,75.000000,66.75,64.75,Completed,Mr. David,Dhaka,206.500000,0.614094,F,611.250000,2024.0,6.0,7.0,57.0
13,PH0014,Urmi Akter,98.000000,78.00,88.00,Completed,Mr. David,Sylhet,264.000000,1.000000,A+,772.000000,2024.0,1.0,4.0,79.0
14,PH0015,Wahiduzzaman,37.000000,67.00,67.00,Completed,Mr. David,Rajshahi,171.000000,0.375839,F,543.000000,2024.0,2.0,22.0,84.0
15,PH0016,Ziaur Rahman,34.000000,88.00,91.00,Completed,Ms. Salma,Rajshahi,213.000000,0.657718,F,693.000000,2024.0,3.0,23.0,90.0
16,PH0017,Afsana Mimi,27.000000,66.75,64.75,Completed,Mr. David,Khulna,158.500000,0.291946,F,515.250000,2024.0,1.0,18.0,58.0
17,PH0018,Babul Ahmed,71.166667,78.00,78.00,Completed,Mr. David,Dhaka,227.166667,0.752796,F,688.333333,2024.0,6.0,23.0,89.0
18,PH0019,Faria Rahman,55.000000,77.00,77.00,In Progress,Mr. Karim,Sylhet,209.000000,0.630872,F,649.000000,2024.0,4.0,19.0,120.0
19,PH0020,Tariq Hasan,65.000000,87.00,87.00,Completed,Mr. Karim,Khulna,239.000000,0.832215,F,739.000000,2024.0,7.0,21.0,82.0
20,NaN,Unknown,71.166667,66.75,64.75,NaN,NaN,NaN,202.666667,0.588367,F,603.583333,NaN,NaN,NaN,NaN

In [294]:
df['FinishedDate'] = pd.to_datetime(df['FinishedDate'])
df['Total time taken to complete'] = (df['FinishedDate'] - df['EnrollmentDate']).dt.days

In [233]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Scaled Marks,Grade,Exceptional Marks,Enrolment Year,Enrolment Month,Enrolment Day,Total time taken to complete
0,PH0001,Alif Rahman,85.500000,88.00,88.00,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,261.500000,0.983221,A+,787.000000,2024.0,9.0,1.0,113.0
1,PH0002,Fatima Akhter,66.500000,66.75,64.75,In Progress,2024-08-11,2024-11-07,Mr. Karim,Dhaka,198.000000,0.557047,F,594.250000,2024.0,8.0,11.0,88.0
2,PH0003,Imran Hossain,78.000000,78.00,76.00,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,232.000000,0.785235,F,696.000000,2024.0,5.0,8.0,92.0
3,PH0004,Jannatul Ferdous,79.000000,44.00,44.00,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,167.000000,0.348993,F,466.000000,2024.0,7.0,5.0,80.0
4,PH0005,Kamal Uddin,65.000000,98.00,98.00,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,261.000000,0.979866,A+,816.000000,2024.0,2.0,1.0,76.0
5,PH0006,Laila Begum,90.000000,13.00,13.00,In Progress,2024-09-07,2024-12-31,Mr. David,Khulna,116.000000,0.006711,F,271.000000,2024.0,9.0,7.0,115.0
6,PH0007,Mahmudul Hasan,85.000000,98.00,33.00,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,216.000000,0.677852,F,661.000000,2024.0,6.0,7.0,43.0
7,PH0008,Nadia Islam,71.166667,66.75,98.00,In Progress,2024-03-22,2024-05-01,Ms. Salma,Khulna,235.916667,0.811521,F,703.333333,2024.0,3.0,22.0,40.0
8,PH0009,Omar Faruq,98.000000,33.00,33.00,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,164.000000,0.328859,F,427.000000,2024.0,2.0,12.0,117.0
9,PH0010,Priya Sharma,99.000000,8.00,8.00,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,115.000000,0.000000,F,254.000000,2024.0,6.0,19.0,61.0
10,PH0011,Rahim Sheikh,66.000000,76.00,64.75,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,206.750000,0.615772,F,630.250000,2024.0,3.0,14.0,89.0
11,PH0012,Sadia Chowdhury,78.000000,57.00,57.00,In Progress,2024-08-04,2024-10-25,Mr. Karim,Sylhet,192.000000,0.516779,F,555.000000,2024.0,8.0,4.0,82.0
12,PH0013,Tanvir Ahmed,75.000000,66.75,64.75,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,206.500000,0.614094,F,611.250000,2024.0,6.0,7.0,57.0
13,PH0014,Urmi Akter,98.000000,78.00,88.00,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,264.000000,1.000000,A+,772.000000,2024.0,1.0,4.0,79.0
14,PH0015,Wahiduzzaman,37.000000,67.00,67.00,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,171.000000,0.375839,F,543.000000,2024.0,2.0,22.0,84.0
15,PH0016,Ziaur Rahman,34.000000,88.00,91.00,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,213.000000,0.657718,F,693.000000,2024.0,3.0,23.0,90.0
16,PH0017,Afsana Mimi,27.000000,66.75,64.75,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,158.500000,0.291946,F,515.250000,2024.0,1.0,18.0,58.0
17,PH0018,Babul Ahmed,71.166667,78.00,78.00,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,227.166667,0.752796,F,688.333333,2024.0,6.0,23.0,89.0
18,PH0019,Faria Rahman,55.000000,77.00,77.00,In Progress,2024-04-19,2024-08-17,Mr. Karim,Sylhet,209.000000,0.630872,F,649.000000,2024.0,4.0,19.0,120.0
19,PH0020,Tariq Hasan,65.000000,87.00,87.00,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,239.000000,0.832215,F,739.000000,2024.0,7.0,21.0,82.0
20,NaN,Unknown,71.166667,66.75,64.75,NaN,NaT,NaT,NaN,NaN,202.666667,0.588367,F,603.583333,NaN,NaN,NaN,NaN

### 12.9 Pandas Group By

In [295]:
group = df.groupby('Instructor')

In [299]:
df.drop(columns=['StudentID', 'FullName','CompletionStatus'], inplace=True)

In [300]:
group = df.groupby('Instructor')

In [301]:
group.sum()

,Data Structure Marks,Algorithm Marks,Python Marks,Location,Total Marks,Scaled Marks,Grade,Exceptional Marks,Enrolment Year,Enrolment Month,Enrolment Day,Total time taken to complete
Instructor,,,,,,,,,,,,
Mr. David,647.166667,573.50,514.5,SylhetKhulnaChattogramDhakaDhakaSylhetRajshahi...,1735.166667,4.699105,A+FFFFA+FFF,5131.833333,18216.0,39.0,108.0,662.0
Mr. Karim,507.500000,440.75,427.5,DhakaKhulnaDhakaSylhetSylhetSylhetKhulna,1375.750000,3.830537,FFFFFFF,4060.500000,14168.0,39.0,86.0,658.0
Ms. Salma,268.666667,320.75,353.0,KhulnaDhakaKhulnaRajshahi,942.416667,3.237696,A+FFF,2879.333333,8096.0,20.0,54.0,335.0

In [302]:
group.min()

,Data Structure Marks,Algorithm Marks,Python Marks,Location,Total Marks,Scaled Marks,Grade,Exceptional Marks,Enrolment Year,Enrolment Month,Enrolment Day,Total time taken to complete
Instructor,,,,,,,,,,,,
Mr. David,27.0,8.00,8.0,Chattogram,115.0,0.000000,A+,254.0,2024.0,1.0,1.0,43.0
Mr. Karim,55.0,33.00,33.0,Dhaka,164.0,0.328859,F,427.0,2024.0,2.0,4.0,80.0
Ms. Salma,34.0,66.75,76.0,Dhaka,213.0,0.657718,A+,693.0,2024.0,3.0,1.0,40.0

In [303]:
group.max()

,Data Structure Marks,Algorithm Marks,Python Marks,Location,Total Marks,Scaled Marks,Grade,Exceptional Marks,Enrolment Year,Enrolment Month,Enrolment Day,Total time taken to complete
Instructor,,,,,,,,,,,,
Mr. David,99.0,98.0,98.0,Sylhet,264.0,1.000000,F,816.0,2024.0,9.0,23.0,115.0
Mr. Karim,98.0,87.0,87.0,Sylhet,239.0,0.832215,F,739.0,2024.0,8.0,21.0,120.0
Ms. Salma,85.5,88.0,98.0,Rajshahi,261.5,0.983221,F,787.0,2024.0,9.0,23.0,113.0

In [304]:
group.first()

,Data Structure Marks,Algorithm Marks,Python Marks,Location,Total Marks,Scaled Marks,Grade,Exceptional Marks,Enrolment Year,Enrolment Month,Enrolment Day,Total time taken to complete
Instructor,,,,,,,,,,,,
Mr. David,65.0,98.00,98.00,Sylhet,261.0,0.979866,A+,816.00,2024.0,2.0,1.0,76.0
Mr. Karim,66.5,66.75,64.75,Dhaka,198.0,0.557047,F,594.25,2024.0,8.0,11.0,88.0
Ms. Salma,85.5,88.00,88.00,Khulna,261.5,0.983221,A+,787.00,2024.0,9.0,1.0,113.0

In [305]:
group.last()

,Data Structure Marks,Algorithm Marks,Python Marks,Location,Total Marks,Scaled Marks,Grade,Exceptional Marks,Enrolment Year,Enrolment Month,Enrolment Day,Total time taken to complete
Instructor,,,,,,,,,,,,
Mr. David,71.166667,78.0,78.0,Dhaka,227.166667,0.752796,F,688.333333,2024.0,6.0,23.0,89.0
Mr. Karim,65.000000,87.0,87.0,Khulna,239.000000,0.832215,F,739.000000,2024.0,7.0,21.0,82.0
Ms. Salma,34.000000,88.0,91.0,Rajshahi,213.000000,0.657718,F,693.000000,2024.0,3.0,23.0,90.0

### 12.10 Group by Example

In [307]:
mean_marks = group['Total Marks'].mean()

mean_marks

Instructor
Mr. David    192.796296
Mr. Karim    196.535714
Ms. Salma    235.604167
Name: Total Marks, dtype: float64

In [309]:
df['Total Marks'] = df['Total Marks'].fillna(df['Instructor'].map(mean_marks))

df

,Data Structure Marks,Algorithm Marks,Python Marks,Instructor,Location,Total Marks,Scaled Marks,Grade,Exceptional Marks,Enrolment Year,Enrolment Month,Enrolment Day,Total time taken to complete
0,85.500000,88.00,88.00,Ms. Salma,Khulna,261.500000,0.983221,A+,787.000000,2024.0,9.0,1.0,113.0
1,66.500000,66.75,64.75,Mr. Karim,Dhaka,198.000000,0.557047,F,594.250000,2024.0,8.0,11.0,88.0
2,78.000000,78.00,76.00,Ms. Salma,Dhaka,232.000000,0.785235,F,696.000000,2024.0,5.0,8.0,92.0
3,79.000000,44.00,44.00,Mr. Karim,Khulna,167.000000,0.348993,F,466.000000,2024.0,7.0,5.0,80.0
4,65.000000,98.00,98.00,Mr. David,Sylhet,261.000000,0.979866,A+,816.000000,2024.0,2.0,1.0,76.0
5,90.000000,13.00,13.00,Mr. David,Khulna,116.000000,0.006711,F,271.000000,2024.0,9.0,7.0,115.0
6,85.000000,98.00,33.00,Mr. David,Chattogram,216.000000,0.677852,F,661.000000,2024.0,6.0,7.0,43.0
7,71.166667,66.75,98.00,Ms. Salma,Khulna,235.916667,0.811521,F,703.333333,2024.0,3.0,22.0,40.0
8,98.000000,33.00,33.00,Mr. Karim,Dhaka,164.000000,0.328859,F,427.000000,2024.0,2.0,12.0,117.0
9,99.000000,8.00,8.00,Mr. David,Dhaka,115.000000,0.000000,F,254.000000,2024.0,6.0,19.0,61.0
10,66.000000,76.00,64.75,Mr. Karim,Sylhet,206.750000,0.615772,F,630.250000,2024.0,3.0,14.0,89.0
11,78.000000,57.00,57.00,Mr. Karim,Sylhet,192.000000,0.516779,F,555.000000,2024.0,8.0,4.0,82.0
12,75.000000,66.75,64.75,Mr. David,Dhaka,206.500000,0.614094,F,611.250000,2024.0,6.0,7.0,57.0
13,98.000000,78.00,88.00,Mr. David,Sylhet,264.000000,1.000000,A+,772.000000,2024.0,1.0,4.0,79.0
14,37.000000,67.00,67.00,Mr. David,Rajshahi,171.000000,0.375839,F,543.000000,2024.0,2.0,22.0,84.0
15,34.000000,88.00,91.00,Ms. Salma,Rajshahi,213.000000,0.657718,F,693.000000,2024.0,3.0,23.0,90.0
16,27.000000,66.75,64.75,Mr. David,Khulna,158.500000,0.291946,F,515.250000,2024.0,1.0,18.0,58.0
17,71.166667,78.00,78.00,Mr. David,Dhaka,227.166667,0.752796,F,688.333333,2024.0,6.0,23.0,89.0
18,55.000000,77.00,77.00,Mr. Karim,Sylhet,209.000000,0.630872,F,649.000000,2024.0,4.0,19.0,120.0
19,65.000000,87.00,87.00,Mr. Karim,Khulna,239.000000,0.832215,F,739.000000,2024.0,7.0,21.0,82.0
20,71.166667,66.75,64.75,NaN,NaN,202.666667,0.588367,F,603.583333,NaN,NaN,NaN,NaN