### Filtering Based on String

In [11]:
import pandas as pd

data ={
    "Name": ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan', 'Judy',],
    "city": ['New York', 'Los Angeles', 'New Delhi', 'Houston', 'Newark', 'New Orleans', 'San Antonio', 'San Diego', 'Dallas', 'H Los Angeles'],
    "Department": ['HR', 'Finance', 'IT', 'Marketing', 'Sales', 'HR', 'Finance', 'IT', 'Marketing', 'Sales'],
    "Salary": [70000, 80000, 90000, 75000, 85000, 72000, 82000, 92000, 77000, 87000]
}

df = pd.DataFrame(data)
print(df)

      Name           city Department  Salary
0    Alice       New York         HR   70000
1      Bob    Los Angeles    Finance   80000
2  Charlie      New Delhi         IT   90000
3    David        Houston  Marketing   75000
4      Eve         Newark      Sales   85000
5    Frank    New Orleans         HR   72000
6    Grace    San Antonio    Finance   82000
7    Heidi      San Diego         IT   92000
8     Ivan         Dallas  Marketing   77000
9     Judy  H Los Angeles      Sales   87000

In [4]:
df.loc[df['city'].str.contains("New")]

      Name         city Department  Salary
0    Alice     New York         HR   70000
2  Charlie    New Delhi         IT   90000
4      Eve       Newark      Sales   85000
5    Frank  New Orleans         HR   72000

In [10]:
df.loc[df['city'].str.contains("new", case=False)] # case=False means it will ignore the case sensitivity. So it will match "New", "new", "NEW", etc.

      Name         city Department  Salary
0    Alice     New York         HR   70000
2  Charlie    New Delhi         IT   90000
4      Eve       Newark      Sales   85000
5    Frank  New Orleans         HR   72000

In [ ]:
#start with "Los"
df.loc[df['city'].str.contains(r"^Los")] # ^ means starts with

  Name         city Department  Salary
1  Bob  Los Angeles    Finance   80000

In [15]:
#end with rk
df.loc[df['city'].str.contains(r"rk$")] # $ means ends with

    Name      city Department  Salary
0  Alice  New York         HR   70000
4    Eve    Newark      Sales   85000

In [16]:
#name start with vowel
df.loc[df['Name'].str.contains(r"^[AEIOUaeiou]")] # ^ means starts with and [AEIOUaeiou] means any of the characters in the brackets

    Name      city Department  Salary
0  Alice  New York         HR   70000
4    Eve    Newark      Sales   85000
8   Ivan    Dallas  Marketing   77000

In [ ]:
#start with New or los
df.loc[df['city'].str.contains(r"(^New|Los)")] # ^ means starts with and (New|Los) means either New or Los

/var/folders/gg/nmkjyktn2ks12wkqpnyjr7mc0000gn/T/ipykernel_39647/703711840.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df.loc[df['city'].str.contains(r"(New|Los)")] # ^ means starts with and (New|Los) means either New or Los

      Name           city Department  Salary
0    Alice       New York         HR   70000
1      Bob    Los Angeles    Finance   80000
2  Charlie      New Delhi         IT   90000
4      Eve         Newark      Sales   85000
5    Frank    New Orleans         HR   72000
9     Judy  H Los Angeles      Sales   87000