### Filtering Based on String

In [11]:
import pandas as pd

data ={
    "Name": ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan', 'Judy',],
    "city": ['New York', 'Los Angeles', 'New Delhi', 'Houston', 'Newark', 'New Orleans', 'San Antonio', 'San Diego', 'Dallas', 'H Los Angeles'],
    "Department": ['HR', 'Finance', 'IT', 'Marketing', 'Sales', 'HR', 'Finance', 'IT', 'Marketing', 'Sales'],
    "Salary": [70000, 80000, 90000, 75000, 85000, 72000, 82000, 92000, 77000, 87000]
}

df = pd.DataFrame(data)
print(df)

      Name           city Department  Salary
0    Alice       New York         HR   70000
1      Bob    Los Angeles    Finance   80000
2  Charlie      New Delhi         IT   90000
3    David        Houston  Marketing   75000
4      Eve         Newark      Sales   85000
5    Frank    New Orleans         HR   72000
6    Grace    San Antonio    Finance   82000
7    Heidi      San Diego         IT   92000
8     Ivan         Dallas  Marketing   77000
9     Judy  H Los Angeles      Sales   87000

In [4]:
df.loc[df['city'].str.contains("New")]

      Name         city Department  Salary
0    Alice     New York         HR   70000
2  Charlie    New Delhi         IT   90000
4      Eve       Newark      Sales   85000
5    Frank  New Orleans         HR   72000

In [10]:
df.loc[df['city'].str.contains("new", case=False)] # case=False means it will ignore the case sensitivity. So it will match "New", "new", "NEW", etc.

      Name         city Department  Salary
0    Alice     New York         HR   70000
2  Charlie    New Delhi         IT   90000
4      Eve       Newark      Sales   85000
5    Frank  New Orleans         HR   72000

In [ ]:
#start with "Los"
df.loc[df['city'].str.contains(r"^Los")] # ^ means starts with

  Name         city Department  Salary
1  Bob  Los Angeles    Finance   80000

In [15]:
#end with rk
df.loc[df['city'].str.contains(r"rk$")] # $ means ends with

    Name      city Department  Salary
0  Alice  New York         HR   70000
4    Eve    Newark      Sales   85000

In [16]:
#name start with vowel
df.loc[df['Name'].str.contains(r"^[AEIOUaeiou]")] # ^ means starts with and [AEIOUaeiou] means any of the characters in the brackets

    Name      city Department  Salary
0  Alice  New York         HR   70000
4    Eve    Newark      Sales   85000
8   Ivan    Dallas  Marketing   77000

In [ ]:
#start with New or los
df.loc[df['city'].str.contains(r"(^New|Los)")] # ^ means starts with and (New|Los) means either New or Los

/var/folders/gg/nmkjyktn2ks12wkqpnyjr7mc0000gn/T/ipykernel_39647/703711840.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df.loc[df['city'].str.contains(r"(New|Los)")] # ^ means starts with and (New|Los) means either New or Los

      Name           city Department  Salary
0    Alice       New York         HR   70000
1      Bob    Los Angeles    Finance   80000
2  Charlie      New Delhi         IT   90000
4      Eve         Newark      Sales   85000
5    Frank    New Orleans         HR   72000
9     Judy  H Los Angeles      Sales   87000

 #### 12.2 Adding new Column and Saving the File

In [25]:
import pandas as pd
df = pd.read_csv('student_completed_data.csv')

In [26]:
#adding a new columnn with constant value
df['Country'] = 'Bangladesh'
df.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Country
0,PH0001,Alif Rahman,85.5,88.0,88.0,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,Bangladesh
1,PH0002,Fatima Akhter,66.5,NaN,NaN,In Progress,2024-08-11,2024-11-07,Mr. Karim,Dhaka,Bangladesh
2,PH0003,Imran Hossain,78.0,78.0,76.0,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,Bangladesh
3,PH0004,Jannatul Ferdous,79.0,44.0,44.0,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,Bangladesh
4,PH0005,Kamal Uddin,65.0,98.0,98.0,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,Bangladesh

In [27]:
#total marks
df['Total Marks'] = df['Data Structure Marks'] + df['Algorithm Marks'] + df['Python Marks']

In [28]:
df.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Country,Total Marks
0,PH0001,Alif Rahman,85.5,88.0,88.0,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,Bangladesh,261.5
1,PH0002,Fatima Akhter,66.5,NaN,NaN,In Progress,2024-08-11,2024-11-07,Mr. Karim,Dhaka,Bangladesh,NaN
2,PH0003,Imran Hossain,78.0,78.0,76.0,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,Bangladesh,232.0
3,PH0004,Jannatul Ferdous,79.0,44.0,44.0,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,Bangladesh,167.0
4,PH0005,Kamal Uddin,65.0,98.0,98.0,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,Bangladesh,261.0

In [30]:
import numpy as np
#A+ in Data Structure if marks >= 80
df['Data Structure Grade'] = np.where(df['Data Structure Marks'] >= 80, 'A+', np.where(df['Data Structure Marks'] >= 70, 'A', np.where(df['Data Structure Marks'] >= 60, 'B', np.where(df['Data Structure Marks'] >= 50, 'C', np.where(df['Data Structure Marks'] >= 40, 'D', 'F')))))
df.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Country,Total Marks,Data Structure Grade
0,PH0001,Alif Rahman,85.5,88.0,88.0,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,Bangladesh,261.5,A+
1,PH0002,Fatima Akhter,66.5,NaN,NaN,In Progress,2024-08-11,2024-11-07,Mr. Karim,Dhaka,Bangladesh,NaN,B
2,PH0003,Imran Hossain,78.0,78.0,76.0,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,Bangladesh,232.0,A
3,PH0004,Jannatul Ferdous,79.0,44.0,44.0,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,Bangladesh,167.0,A
4,PH0005,Kamal Uddin,65.0,98.0,98.0,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,Bangladesh,261.0,B

In [31]:
#first Name
df['First Name'] = df['FullName'].str.split().str[0]
df.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Country,Total Marks,Data Structure Grade,First Name
0,PH0001,Alif Rahman,85.5,88.0,88.0,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,Bangladesh,261.5,A+,Alif
1,PH0002,Fatima Akhter,66.5,NaN,NaN,In Progress,2024-08-11,2024-11-07,Mr. Karim,Dhaka,Bangladesh,NaN,B,Fatima
2,PH0003,Imran Hossain,78.0,78.0,76.0,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,Bangladesh,232.0,A,Imran
3,PH0004,Jannatul Ferdous,79.0,44.0,44.0,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,Bangladesh,167.0,A,Jannatul
4,PH0005,Kamal Uddin,65.0,98.0,98.0,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,Bangladesh,261.0,B,Kamal

In [32]:
df.to_csv('new_data.csv')

### 12.3 Checking Duplicates and Null Values in DF

In [37]:
import pandas as pd
data = {
    "Name": ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Bob', 'Grace', 'Heidi', 'David', 'Judy',],
    "city": ['New York', 'Los Angeles', 'New Delhi', 'Houston', 'Newark', 'New Orleans', 'San Antonio', 'San Diego', 'Dallas', 'H Los Angeles'],
    "score": [85, 90, 78, 92, 88, 95, 80, 91, 89, 94]
}

df = pd.DataFrame(data)
print(df)

      Name           city  score
0    Alice       New York     85
1      Bob    Los Angeles     90
2  Charlie      New Delhi     78
3    David        Houston     92
4      Eve         Newark     88
5      Bob    New Orleans     95
6    Grace    San Antonio     80
7    Heidi      San Diego     91
8    David         Dallas     89
9     Judy  H Los Angeles     94

In [38]:
#Unique and nunique
df['Name'].unique() # unique values in the Name column
len(df['Name'].unique()) # number of unique values in the Name column

8

In [49]:
df1 = pd.read_csv('new_data.csv')
print(df1.head())

   Unnamed: 0 StudentID          FullName  Data Structure Marks  \
0           0    PH0001       Alif Rahman                  85.5
1           1    PH0002     Fatima Akhter                  66.5
2           2    PH0003     Imran Hossain                  78.0
3           3    PH0004  Jannatul Ferdous                  79.0
4           4    PH0005       Kamal Uddin                  65.0

   Algorithm Marks  Python Marks CompletionStatus EnrollmentDate FinishedDate  \
0             88.0          88.0        Completed     2024-09-01   2024-12-23
1              NaN           NaN      In Progress     2024-08-11   2024-11-07
2             78.0          76.0        Completed     2024-05-08   2024-08-08
3             44.0          44.0        Completed     2024-07-05   2024-09-23
4             98.0          98.0        Completed     2024-02-01   2024-04-17

  Instructor Location     Country  Total Marks Data Structure Grade First Name
0  Ms. Salma   Khulna  Bangladesh        261.5                   A+       Alif
1  Mr. Karim    Dhaka  Bangladesh          NaN                    B     Fatima
2  Ms. Salma    Dhaka  Bangladesh        232.0                    A      Imran
3  Mr. Karim   Khulna  Bangladesh        167.0                    A   Jannatul
4  Mr. David   Sylhet  Bangladesh        261.0                    B      Kamal

In [46]:
print(len(df1['Data Structure Marks'].unique())) # number of unique values in the Data Structure Marks column

print(df1['Data Structure Marks'].nunique()) # number of unique values in the Data Structure Marks column

16
15

### check null

In [51]:
df1[df1['Data Structure Marks'].isnull()]

,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Country,Total Marks,Data Structure Grade,First Name
7,7,PH0008,Nadia Islam,NaN,NaN,98.0,In Progress,2024-03-22,2024-05-01,Ms. Salma,Khulna,Bangladesh,NaN,F,Nadia
17,17,PH0018,Babul Ahmed,NaN,78.0,78.0,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,Bangladesh,NaN,F,Babul

In [52]:
df1['Data Structure Marks'].isnull()# check if there are any missing values in the DataFrame

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17     True
18    False
19    False
Name: Data Structure Marks, dtype: bool

### 12.4 Handling Duplicates Values

In [75]:
import pandas as pd
data = {
    "Name": ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Bob', 'Alice', 'Heidi', 'David', 'Judy',],
    "city": ['New York', 'Los Angeles', 'New Delhi', 'Houston', 'Newark', 'Los Angeles', 'San Antonio', 'San Diego', 'Dallas', 'New York'],
    "score": [85, 90, 78, 92, 85, 90, 80, 91, 89, 94]
}
df = pd.DataFrame(data)
print(df)

      Name         city  score
0    Alice     New York     85
1      Bob  Los Angeles     90
2  Charlie    New Delhi     78
3    David      Houston     92
4      Eve       Newark     85
5      Bob  Los Angeles     90
6    Alice  San Antonio     80
7    Heidi    San Diego     91
8    David       Dallas     89
9     Judy     New York     94

In [76]:
df.duplicated().sum() # number of duplicate rows in the DataFrame

np.int64(1)

In [77]:
# delete duplicate rows
df.drop_duplicates()

      Name         city  score
0    Alice     New York     85
1      Bob  Los Angeles     90
2  Charlie    New Delhi     78
3    David      Houston     92
4      Eve       Newark     85
6    Alice  San Antonio     80
7    Heidi    San Diego     91
8    David       Dallas     89
9     Judy     New York     94

In [78]:
# premanently delete duplicate rows
df.drop_duplicates(inplace=True)
df

      Name         city  score
0    Alice     New York     85
1      Bob  Los Angeles     90
2  Charlie    New Delhi     78
3    David      Houston     92
4      Eve       Newark     85
6    Alice  San Antonio     80
7    Heidi    San Diego     91
8    David       Dallas     89
9     Judy     New York     94

In [86]:
df

      Name         city  score
0    Alice     New York     85
1      Bob  Los Angeles     90
2  Charlie    New Delhi     78
3    David      Houston     92
4      Eve       Newark     85
6    Alice  San Antonio     80
7    Heidi    San Diego     91
8    David       Dallas     89
9     Judy     New York     94

In [91]:
# name er basis a delete duplicate rows
df.drop_duplicates(subset=['Name'],keep='last')

      Name         city  score
1      Bob  Los Angeles     90
2  Charlie    New Delhi     78
4      Eve       Newark     85
6    Alice  San Antonio     80
7    Heidi    San Diego     91
8    David       Dallas     89
9     Judy     New York     94

In [92]:
df.drop_duplicates(subset=['city'],keep='last')

      Name         city  score
1      Bob  Los Angeles     90
2  Charlie    New Delhi     78
3    David      Houston     92
4      Eve       Newark     85
6    Alice  San Antonio     80
7    Heidi    San Diego     91
8    David       Dallas     89
9     Judy     New York     94